# Generated by Django 6.0.5 on 2026-06-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitemvoidrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saleitemvoidrequest',
            new_name='sales_salei_status_998e55_idx',
            old_name='sales_itemv_status_d1b6e0_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitemvoidrequest',
            new_name='sales_salei_sale_id_96dcde_idx',
            old_name='sales_itemv_sale_3b7405_idx',
        ),
    ]
