# Generated by Django 5.2.15 on 2026-07-04 06:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='max_discount_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount allowed (even if % calculates higher).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_final_total_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Minimum final total as % of subtotal (e.g., 10 = can't discount more than 90%). 0 = no limit.", max_digits=5),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_items_required',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of items in cart to qualify for this discount.'),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum subtotal required for this discount to apply.', max_digits=12),
        ),
    ]
