# Generated by Django 5.2.15 on 2026-07-04 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_discount_max_discount_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='min_final_total_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Minimum final total as % of subtotal (e.g., 10 = can't discount more than 90%). 0 = no limit.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_items_required',
            field=models.PositiveIntegerField(default=2, help_text='Minimum number of items in cart to qualify for this discount.'),
        ),
    ]
