# Generated by Django 5.2.15 on 2026-06-29 11:51

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=apps.catalog.models.generate_sku, editable=False, max_length=20, unique=True),
        ),
    ]
