# Generated by Django 5.2.15 on 2026-07-03 09:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplier unit cost used for inventory valuation and profit estimates.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Automatic low-stock threshold used for alerts and reorder reports.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer-facing unit price used at checkout.', max_digits=12),
        ),
    ]
